### ISSUE TITLE
Fields for CSV\AVERY LABEL output do not change even if the configuration file is updated.

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/land-use-public-notification#17]
Fields for CSV\AVERY LABEL output do not change even if the configuration file is updated.

When labels and CSV's are created the fields that are populated are derived from the config.js. Although, the fields are updated to use all the parameters. Only the 

//Fields for Avery labels
AveryFieldsCollection: ["PARCELID", "OWNERNME1", "OWNERNME2", "PSTLADDRESS", "PSTLCITY" , "PSTLSTATE" , "PSTLZIP5"],

**Comment by LindsayThomas** [comment]
NIM097968

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 

We are unable to reproduce this. We tried configuring different combinations of fields in AveryFieldsCollection and we were able to generate PDF and CSV output that reflected the changed fields. Can you please provide steps to reproduce.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam 


Repo Steps
Look at config.js 
Notice that PSTLCITY" , "PSTLSTATE" , "PSTLZIP5 are configured
AveryFieldsCollection: ["PARCELID", "OWNERNME1", "OWNERNME2", "PSTLADDRESS", "PSTLCITY" , "PSTLSTATE" , "PSTLZIP5"],
In the app http://tryitlive.arcgis.com/PublicNotification/
select a parcel, 100 buffer
check only occupants (do not check owners) 
check avery labels and csv
the output will only show 
PARCELID", "OWNERNME1", "OWNERNME2", "PSTLADDRESS", 
It is missing PSTLCITY" , "PSTLSTATE" , "PSTLZIP5

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 

This feature is as-designed. 

When only occupants are selected, the pdf will display fields configured in OccupantFields tag.
```javascript
      //Label to be displayed for Occupant
      OccupantLabel: "Occupant",

     //Fields of the occupant
     OccupantFields: "PARCELID,SITEADDRESS",
```

The occupant label is used to display the default label in the popup. User can modify this label in the popup. In the pdf, the occupant label is always displayed on the second line.

Please confirm.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam I think this was an issue from the "original" application from a few years back. This is no longer an issue.
