### ISSUE TITLE
Popups should be centered on the polygon, and lines

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/land-use-public-notification#20]
This could be a larger design change. Based on how we handle the popups in all LG apps

**Comment by LindsayThomas** [comment]
Work with CB to define what this would look like for lines, polys, and points.

**Comment by LindsayThomas** [comment]
@busbus Do you have any feedback on this?

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas @busbus 
For polygons we can anchor the popup to the centroid of the polygon. 
For lines, the centroid may be a problem depending on the shape of the line. The centroid will be on the line only if it is a straight line. A curved line (roads in this case) will have its centroid outside the line.
We looked at arcgis map viewer behavior for popups of line layers and saw that AGOL uses centroid for lines but Portal Map Viewer (10.3.1) uses the first point of the line feature to anchor the popup.

Please have a look at these screen captures and let us know what you'd prefer.

**AGOL Map Viewer (uses centroid of line)**  
![line-popup-agol](https://cloud.githubusercontent.com/assets/2959186/11206237/a6895d66-8d33-11e5-89b9-fe50bc707e5f.gif)  

**Portal Map Viewer (uses first point of line feature)**  
![line-popup-portal](https://cloud.githubusercontent.com/assets/2959186/11207741/ea03b128-8d3c-11e5-8bc3-07dcf93e9637.gif)

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam for Lines please use the AGOL Map Viewer (uses centroid of line) approach. 

What happens when multiple polygons are selected?

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 

With multi-part polygons, the centroid may not lie within any of the parts. 

It is the same case for a line, polygon, or multi-part line/polygon feature, as the centroid is not guaranteed to be on/inside the feature. Depending on the shape of polygon, the centroid may lie outside the polygon. For e.g, an L-shaped or C-shaped polygon will have its centroid outside the polygon.

The way AGOL map viewer calculates the centroid is by getting the center point of the feature's extent (minimum bounding rectangle). This is why you see in the screenvideos above, that the infowindow does not display on the feature.

**Comment by busbus** [comment]
@CTLocalGovTeam It appears that the application is using the Portal Map Viewer approach still (first point on the line).  @LindsayThomas specified the AGOL Map viewer method.

Please confirm.

**Comment by CTLocalGovTeam** [comment]
@busbus, @LindsayThomas 
This behavior and its associated problems were discussed on a call. We had the idea that this was to remain unchanged. Anyways, this is a very minor code change. 
However, the effect of this will be that the info-window will display on the lines (touching) only if they are exactly straight. When an entire stretch of road is searched by name and selected, it is always likely that the road is not straight. Hence, the info-window will almost always lie outside the line. 

Please confirm if we should go ahead and include the AGOL Map Viewer method.

**Comment by LindsayThomas** [comment]
@ChrisBuscaglia

**Comment by ChrisBuscaglia** [comment]
Please leave as-is
