### ISSUE TITLE
Removing a basemap causes the basemap switcher to break

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/land-use-public-notification#29]
Removing one of the Basemaps from the array list of basempas does not work. Application basemap switcher will lock up

The below snippet should work but it doesn't.
      BaseMapLayers: [{
            Key: "parcelMap",
            ThumbnailSource: "js/library/themes/images/parcelmap.png",
            Name: "Parcel Map",
            MapURL: "http://tryitlive.arcgis.com/arcgis/rest/services/ParcelPublicAccessMI/MapServer"
        },{
            Key: "imagery",
            ThumbnailSource: "js/library/themes/images/imagery.png",
            Name: "Imagery",
            MapURL: "http://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer"
        }],

@NikkiGolding @lindsayking FYI, this could be an issue in the new style app's as well.

**Comment by LindsayThomas** [comment]
Also, if BaseMapLayers: [{ }], is configured then the basemap switcher will not appear

**Comment by busbus** [comment]
Fixed with 4.7
