### ISSUE TITLE
Mailing labels fail to be created when using a large overlay layer as buffer input using IE 10/11

### ISSUE THREAD

**Issue by busbus** [Esri/land-use-public-notification#32]
Open the LUPN application using IE 10/11 using the sample services provided - 

http://tryitlive.arcgis.com/PublicNotification/

1. Search for Naperville North High School
2. Select the Naperville North High School
3. Notify with the following as input

(Ignore mismatched screenshot)
![lupn](https://cloud.githubusercontent.com/assets/5614261/5347932/b555b4f0-7ee0-11e4-9f25-177c061ca2c7.jpg)

4. Parcels are selected (as part of the buffer) but no output (PDF) is created

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 
Searching for Bloomfield Hills does not return any results on tryitlive.
We are unable to reproduce this on IE 10/11. We are able to generate PDFs by searching for 'school' and selecting any school from the list of results in IE 10/11.
Also, the http://ec2-54-190-67-63.us-west-2.compute.amazonaws.com/publicnotification103/ link is not working.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam We updated repo steps for naperville data. Please search for
 Naperville North High School  (see steps above)

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas @busbus 
We are able to reproduce this.

This appears to be an issue with IE 10/11 browser and its ability to load and display pdf documents with large number of pages.

The pdf generated for Naperville North High School contains 500 pages. We see that a new tab opens in IE but the document does not load. If you copy the URL in the address bar and paste it in chrome or firefox, the pdf is displayed. So, the geoprocessing service is able to generate the pdf successfully, but IE is unable to load it.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Is there a way to "known" this is happening in IE10 and 11?  Would it be possible to display a msg telling the user to use another browser for large requests?

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas @busbus 
Yes, we could display a message to use another browser when the number of labels exceed a pre-determined value for e.g., 1000 (approximately 30 pages in pdf). 

We can inform the user that IE may not load the document, and if it does not load, please try a different browser.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam sounds good

**Comment by busbus** [comment]
Fixed with 4.7
