### ISSUE TITLE
Print Doesn't work on Chrome

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/land-use-public-notification#33]
The print icon is not working:  the app fails on line 72 of printMap.js because window.showModalDialog is undefined, and the console reports “Uncaught TypeError: undefined is not a function”.  This function used to be part of the window object, but it was deprecated some years back and has now been removed from Chrome.

@MikeTschudi How big of change is this?

FYI @busbus
<span><b>Salesforce ID:</b> BUG-000088357</span><br/>

**Comment by skrishn** [comment]
@mike:  Please review the code.

**Comment by skrishn** [comment]
@MikeTschudi: Please review the code.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam This was miss assigned. Can we include this in the estimate?

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 
We have included this in the estimate.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam There is a fix for this print issue in the branch https://github.com/Esri/land-use-public-notification/commit/9eb56529be719bd0c4819e85accb195c693a8861 . This can be used if it will save time/and you consider it an acceptable solution (meeting best practices, etc). However, it should be code reviewed and tested as part of the task order. 

FYI @ScottOppmann

**Comment by busbus** [comment]
Fixed with V4.7
