### ISSUE TITLE
Services on amazon apparently broken

### ISSUE THREAD

**Issue by stopyaks** [Esri/land-use-public-notification#37]
All of a sudden the gp server for creating avery labels has stopped working. It was pointed at the default url on amazonaws.com which doesn't seem to be there anymore? The example on the github site is working though.

**Comment by LindsayThomas** [comment]
@stopyaks Are you using the TryItlive version of the application? 

I updated our backend services and updated all the application dependencies including the repo config.js as well as the tryitlive application.
