### ISSUE TITLE
when DISTRCTNAME field is updated in the LGIM we need to update config.js too

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/land-use-public-notification#38]
When DISTRCTNAME field is updated in the LGIM we need to update config.js too. 

@busbus FYI

@LindsayThomas (Link once we get the triage number)

**Comment by LindsayThomas** [comment]
BUG-000088915

**Comment by LindsayThomas** [comment]
@ScottOppmann @ChrisBuscaglia The LGIM isn't being updated for the February release, so we should defer this until TBD correct?

**Comment by ScottOppmann** [comment]
@LindsayThomas @ChrisBuscaglia 

Correct - No LGIM updates in Feb.  Mike did update sample data for water, but no schema changes.  We are going to update all admin boundaries in May release, so we can tackle this issue then.
