### ISSUE TITLE
Assess whether to update to reportlab 3.0 for 2.7 OR removing reportlab dependency

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/land-use-public-notification#41]
Access whether to update to reportlab 3.0 for 2.7 OR removing reportlab dependency

**Comment by allisonmuise** [comment]
@LindsayThomas : IMO it is not realistic to remove the reportlab dependency without removing the creation of pdf files. ReportLab is by far the best (only?) way to create these documents. Upgrading shouldn't be an issue. They are excellent about backwards compatibility.

**Comment by LindsayThomas** [comment]
@allisonmuise We have no intention of changing the spec. This is just a ticket to access our options. It may be the only way but what to look at this since the last time it was accessed was 2010 or earlier

**Comment by LindsayThomas** [comment]
Just going to update the version
