### ISSUE TITLE
Assess whether or not there is a  hardcoded dependency on "LowParcelID" in the application and in the GP tools

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/land-use-public-notification#45]
Validate if there is a hardcoded dependency on "LowParcelID" for the GP tools and \or the application

@busbus This was an issue in the old app. I think we fixed it, but I am not sure. We should test it out. If there is a hardcoded dependency then we need to remove it.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 
We investigated this and can confirm that there is no hard coded dependency on "LowParcelID" in the gptools and application. It is a required configurable parameter.

![image](https://cloud.githubusercontent.com/assets/2959186/10845195/bb04c674-7f2b-11e5-9588-03b6f93fe045.png)

The lowest tax parcel identification number is an integral part of the Local Gov Information Model, and is used to uniquely identify the condominium polygon in the parcel fabric. 

To verify that the field name is not hard coded, we altered the field name *LOWPARCELID* without modifying the ids in the table and updated the same in configuration file. The app worked as expected.

Please confirm if this is what you were trying to accomplish.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Okay. Thanks that makes sense.

========================
Note to LT and CB this works with naperville data (Using one Parcel ID field) 

            ParcelInformation: {
                LowParcelIdentification: "PARCELID",
                ParcelIdentification: "PARCELID",
                AliasParcelField: "Parcel Identification Number",
                SiteAddress: "SITEADDRESS"
