### ISSUE TITLE
Enhancement Address Selection

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/land-use-public-notification#46]
quote from @ScottOppmann "Here is what I would envision as we begin to tie parcels to addresses. You buffer the parcels to find all properties included in the notification, then determine which site address points are included in the parcels and then use the site address and mailing address in the notification. It’s a bit complex, but think we will need it as more and more site address information is managed in point features."

Deferred

**Comment by GISTiger** [comment]
I'd just like to leave a note that this would be a very useful enhancement. Using situs only gets one physical address per parcel, so we end up losing a lot without the address points.

As an alternative, would it work if I wrote a SQL view to spatially join address point data to parcel polygons and then publish that as a service? The end result would be stacked polygons for parcels that have multiple address points on it. What would the current configuration do with stacked parcels?
