### ISSUE TITLE
Ensure the GP tools will run successfully in Desktop and produce a valid result.

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/land-use-public-notification#48]
This is an enhancement to better support usability for customers. 

GP tool must run successfully before being published (this works now) 
However, the result produced isn't valid. It would be good to get a default value or the like to ensure we are producing a valid output not just an empty output. 

We have heard from customers that this is confusing.

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 
We are thinking of populating with the gptools with valid default values of addresses so they create valid outputs for both CSV and PDF. The current workflow of publishing these tools remains unchanged. To publish, users will have to run the tools with their default values. It's just that when you execute these tools with their default values, a valid output will be generated, which the users can view.

Just wanted to confirm is this what you had in mind?

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam that is what I had in mind. 
(Also related right now we have the default label as 5160. Should it be avery5160? Regardless let's make the default function correctly)

**Comment by busbus** [comment]
This is confirmed fixed, however - I found it confusing still.  The outputs are written to the scratch workspace/folder, if you don't know what a scratch folder is, you have no idea where to look for the output to check it.  The CSV is a valid ArcMap item and gets added (if you specifically set GP outputs to be added to the Map) but the PDF is lost to wormhole of the scratch folder.

**Comment by ChrisBuscaglia** [comment]
@CTLocalGovTeam Where there any code changes made to the GP tools?  Cannot find any updates to the python code - even though the tools create valid outputs.

**Comment by CTLocalGovTeam** [comment]
@ChrisBuscaglia 
No code change was required to the GP tools. Only the default values for the input parameters were changed. That's why you don't see any updates to the python code.

**Comment by ChrisBuscaglia** [comment]
OK - thanks for confirming.
