### ISSUE TITLE
Support for Windows Edge Browser

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/land-use-public-notification#49]
Support for Windows Edge Browser
Fix any issue related to Edge

@busbus FYI

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 

Assuming you are looking for support of Windows Edge browser for desktops only. Please confirm.

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam We are waiting to get confirmation from some others at Esri on this. However, I don't want this to impact the estimate schedule. Can we get an estimate with Desktop only and Tablet only?

**Comment by LindsayThomas** [comment]
@CTLocalGovTeam Please test Edge Browser on a desktop with Keyboard and mouse.

**Comment by busbus** [comment]
Fixed with 4.7
