### ISSUE TITLE
Locator in toolbar question

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/land-use-public-notification#51]
@CTLocalGovTeam In the config.js is there a switch to turn off the "locator" button in the header?

**Comment by CTLocalGovTeam** [comment]
@LindsayThomas 

There is no switch to turn off the "locator" button. But we can remove the "locator" widget by removing the widegts object from "AppHeaderWidgets" array.

![image](https://cloud.githubusercontent.com/assets/2959186/11365137/7373d05e-92ca-11e5-8e1c-15e1f6606949.png)

**Comment by busbus** [comment]
@LindsayThomas do we want to remove the object form the array by default?  Or comment it out?

**Comment by LindsayThomas** [comment]
@busbus If we can just comment it out then that is my preference. If commenting in the array breaks the application, then I would just remove it but put in the comment section as an option.

**Comment by busbus** [comment]
We'll comment it out - works fine.

**Comment by LindsayThomas** [comment]
update config with this

**Comment by ChrisBuscaglia** [comment]
https://github.com/Esri/land-use-public-notification/commit/b1832ee042698dc9f3dbe0ce141c00944ecc61e1
