### ISSUE TITLE
window.showModalDialog error appearing when attempting to print in Google Chrome

### ISSUE THREAD

**Issue by nhaney90** [Esri/land-use-public-notification#52]
When I run the application in Google Chrome and I click the print button nothing happens. When I check the console the following error message is shown:

"Uncaught TypeError: window.showModalDialog is not a function"

The application works normally in Firefox or IE. My Chrome version is 46.

Note: Nevermind. Didn't see the other issue logged for this behavior.

**Comment by busbus** [comment]
Issue is currently fixed, awaiting future release - thanks for posting.
