### ISSUE TITLE
Convert App To a configurable Geoprocessing Service so ti could be added to a widget in WAB

### ISSUE THREAD

**Issue by joemorocco** [Esri/land-use-public-notification#54]
For utilities – customer notification…

Many, if not most utilities, are required to send out notifications both proactively and reactively based on service outages as well as construction projects.

Example #1 – When a water main breaks and there is a boil water notice (service is shut down), they need to create a mailing / submit a list of customers to customer service, and gather contact information for something like an autodialing system.

Example #2 – Construction project is going to happen – a user would select an area or create a buffer of a feature to get mailing labels . Contact info for a mailing or door hanging tags might be generated from these.  

Example #3 – Conservation notification – residents in something like a watershed or engineering district would be mailed a notification of a program of rebate they could participate in.  

The key to these scenarios is that the underlying data is flexible as well as the workflows for designating the area for generating the mailing labels.  Having a GP tools that would be exposed in something like the Web App Builder would allow for that flexibility.

**Comment by busbus** [comment]
@joemorocco 

This is definitely on the roadmap after our next set of updates, thanks for posting.

Chris

**Comment by ScottOppmann** [comment]
@joemorocco - Just a bit more detail on Chris's note.  In the current version of the app, you could deliver mailing labels for pre-defined boundaries like (watersheds, districts, etc.).  In early 2016, we're shipping a series of updates to the public notification app that will allow users draw their own polygons and start the notification using a newly drawn feature.After we get the next release out, we're going to start looking at how we can provide this functionality in a hosted app.  This will require a hosted label service (working with the GP team) and either a WAB widget or a hosted AGOL app template.
