### ISSUE TITLE
Sharing does not work properly when roads or overlay layers are selected

### ISSUE THREAD

**Issue by lindsayking** [Esri/land-use-public-notification#60]
When features are selected from the Roads or Overlay layers, those features do not display correctly in the shared version of the app.  They are not highlighted and the popup does not display.

Steps to repro for overlay layer:
1) Search for Gregory Middle School
2) Note that polygon features are highlighted on the map and a popup displays
3) Click Share and choose Facebook, Twitter or email
4) Open the shared result. The polygons are not highlighted and the pop-up doesn’t appear in the shared app. 

Steps to repro for roads layer:
1) Search "ogden ave" and then scroll down to the bottom of the candidate list to select the Ogden Ave option under 'Road Centerline'
2) Note the road features are highlighted and a popup displays
3) Share the app through Facebook, Twitter or email
4) Open the shared version.  Note the extent is correct, but no features are highlighted and there is no popup visible.

Note that this is a new issue and does not exist in the [released version](http://tryitlive.arcgis.com/publicnotification/) of the app.

**Comment by ChrisBuscaglia** [comment]
@CTLocalGovTeam How the fix coming?

**Comment by CTLocalGovTeam** [comment]
@ChrisBuscaglia we have fixed this issue and are in the process of delivering code.
