### ISSUE TITLE
Update the references of Land Use Public Notification to Public Notification

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/land-use-public-notification#62]
- [x] Config.js
- [x] default.htm
- [x] localizedstring.js 
- [x] help.htm

**Comment by ChrisBuscaglia** [comment]
https://github.com/Esri/land-use-public-notification/commit/06e9f7836debabdd401cd424acbeedd606a94c44

**Comment by LindsayThomas** [comment]
verified
