### ISSUE TITLE
Can an address points layer be integrated into the Occupant listing for this application?

### ISSUE THREAD

**Issue by CristiDelgado** [Esri/land-use-public-notification#72]
It seems that only the parcel layer is utilized to produce both the property owner list and occupant list.  Thus there is only one occupant address per parcel.  Our parcels have a one to many relationship, many addresses per parcel. Thus, we need to use the parcel layer for property owner listing and intersecting address points layers for the occupant addresses, apt 1, apt 2, etc.

**Comment by ChrisBuscaglia** [comment]
@chris-fox
