### ISSUE TITLE
Notification fails when attempting to notify all property owners

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/land-use-public-notification#73]
Notification fails when attempting to notify all property owners

**Comment by ChrisBuscaglia** [comment]
@CTLocalGovTeam  This fails when drawing a polygon around a large area - over 35000 parcels.

**Comment by CTLocalGovTeam** [comment]
@ChrisBuscaglia 

Can you please provide the steps to reproduce and observed behavior?

**Comment by ChrisBuscaglia** [comment]
yes - just use the draw functionality to create a polygon for the sample data.

**Comment by CTLocalGovTeam** [comment]
@ChrisBuscaglia 

When you draw a polygon over a large area, the app tries to get the parcels within the polygon, which returns 15000 as thats the server limit. Then it tries to identify if there are stacked parcels within the 15000 that were returned, and tries to fetch and add them to the list of parcels to be notified. This is a long running operation and the API is timing out. When this happens, the app notifies only the parcels in the list till it times out and the notification succeeds.

Are you seeing the same behavior? or is the notification failing on your side?
