### ISSUE TITLE
BUG-000103133  The Public Notification template incorrectly prints Avery labels for 'Property Occupants'

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/land-use-public-notification#79]
<div><div>
<span><b>Salesforce ID:</b> BUG-000103133</span><br/>
<span><b>Salesforce Submitter:</b> Bradley Snider</span><br/>
<span><b>Salesforce Submit Date:</b> 2/23/2017 11:35 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Usability</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Local Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.5</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by MikeTschudi** [comment]
Duplicate of #74
