### ISSUE TITLE
BUG-000101045  The Land Use Public Notification template hardcoded parcel ID feld is unable to dynamically generate PDF files based on a user's schema.

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/land-use-public-notification#84]
<div><div>
<span><b>Salesforce ID:</b> BUG-000101045</span><br/>
<span><b>Salesforce Submitter:</b> Nathan Wu</span><br/>
<span><b>Salesforce Submit Date:</b> 11/29/2016 10:57 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Usability</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> Debugged with user's code and found the request in 'infoWindow.js' is hard-coded to query the 'LOWPARCELID' field, and switch all the 'LOWPARCELID' field to the user's field name 'APN'.</span><br/>
<span><b>Product:</b> ArcGIS for Local Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.4.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Please see the the GitHub branch https://github.com/Esri/land-use-public-notification/tree/develop to ensure issue is addressed.</span><br/>
</div></div>

**Comment by LindsayThomas** [comment]
Updated this in Triage on the backend
