### ISSUE TITLE
Setting the buffer to zero most often returns wild results.

### ISSUE THREAD

**Issue by stopyaks** [Esri/land-use-public-notification#85]
Setting the buffer to zero most often returns wild results.

Example:
http://ecgis.eatoncounty.org/PublicNotification

If you set the buffer to zero, the results will be way off, returning a ton of parcels when it should return just the selected one.
Additionally, you can enter crazy values like 000005 without an error. It appears that the validation needs some work but I haven't had any luck with it.

Update:
In the infowidow.js, I replaced all instances of LOWPARCELID with PARCELID and it works fine (so far). There was something squirrelly about building arrays with LOWPARCELID, I guess.

**Comment by ScottOppmann** [comment]
FYI @MikeTschudi @chris-fox @ChrisBuscaglia
