### ISSUE TITLE
Occupant Label not selecting site address but Owner Address

### ISSUE THREAD

**Issue by FireGuyGinge33** [Esri/land-use-public-notification#88]
When trying to create the Occupant Label, it takes the Owner Address and associates it with the Occupant Labels rather than taking the site address and associating it with the Occupant Label. Is there a way to fix that?

**Comment by ChrisBuscaglia** [comment]
@FireGuyGinge33 Just make sure that the you have situs address fields in place of postal city, state, zip in the example below.

 //Fields of the occupant
OccupantFields: "PARCELID, SITEADDRESS, CITY, STATE, ZIP5",
